/* ========================= Data Definitions ========================= */

// Predefined areas for typeahead
const PREDEFINED_AREAS = [
  "Borivali West", "Borivali East", "Dahisar West", "Dahisar East",
"Kandivali West", "Kandivali East", "Malad West", "Malad East",
"Mira Road West", "Mira Raod East", "Goregaon West", "Goregaon East",
"Andheri West", "Andheri East", "Gorai", "Charkop",
"Old MHB", "New MHB", "Babhai", "Kajupada",
"Ashok Van", "Magathane", "Kulupwadi", "IC Colony",
"Kandarpada", "Malvani", "Eksar", "Anand Nagar", "Yogi Nagar"
];

// Predefined doctors
const PREDEFINED_DOCTORS = [
  "Dr. Shruti Gogate",
"Dr. Snehal Sawant",
"Dr. Satish Sawant",
"Dr. Sushama Dubal",
"Dr. Reshma Bhivgude",
"Dr. Sushama Dabhade",
"Dr. Sunil Dabhade",
"Dr. Jagat Shah",
"Dr. Pravin Arlekar",
"Dr. Avinash Diwate",
"Dr. Sejal.p Jain",
"Dr. Maxim D'mello",
"Dr. Anushka Khot"
];

// Predefined care of relationships
const PREDEFINED_CARE_OF = [
"Soni",
"Sumit",
"Prerana",
"Purabiya",
"Anish",
"Ashok Sir",
"Kunal",
"Eva",
"Vaishali Dhumal",
"Kalpana Sister",
"Megha Sister",
"Sindhu Sister",
"Centre Patient"
];

// Predefined phlebotomists
const PREDEFINED_PHLEBOTOMISTS = [
  "Soni",
"Sumit",
"Anish",
"Prerana",
"Kunal",
"Ashok Sir",
"Priya Purabiya",
"Megha Sister",
"Sindhu Sister"
];

/* ========================= Tube Types Definition (Centralized) ========================= */
const TUBE_TYPES = {
  "EDTA": {
    name: "EDTA Tube (Purple)",
    displayName: "EDTA Tube",
    imageUrl: "https://lh3.googleusercontent.com/d/1iHKiKtrFMgpLEkyIRUnhz4cl9LZ9XFux"
  },
  "Fluoride": {
    name: "Fluoride Tube (Grey)",
    displayName: "Fluoride Tube",
    imageUrl: "https://lh3.googleusercontent.com/d/1MZdwsqJlSHhRbVEUrm_TYv4InUWs5kdV"
  },
  "Plain": {
    name: "Plain Tube (Red)",
    displayName: "Plain Tube",
    imageUrl: "https://lh3.googleusercontent.com/d/1O9o_bmtUvZ3cuiOqfRog1wFzYY4UxRkt"
  },
  "Citrate": {
    name: "Citrate Tube (Blue)",
    displayName: "Citrate Tube",
    imageUrl: "https://lh3.googleusercontent.com/d/1_jb-6BP-Dr5W3Aj8DFc6faCaX6tRhC3A"
  },
  "Serum": {
    name: "Serum Tube (Yellow)",
    displayName: "Serum Tube",
    imageUrl: "https://lh3.googleusercontent.com/d/1-9Fvi0XRk92RSAas4uHubJrhvu569UWd"
  },
  "Urine": {
    name: "Urine Container",
    displayName: "Urine Container",
    imageUrl: "https://lh3.googleusercontent.com/d/1bjZq6bvMic2Azyd11-aasyQss3AOeFZw"
  }
};

/* ========================= Test to Tube Mapping ========================= */
const TEST_TUBE_MAPPING = {
  "CBC": ["EDTA"],
  "Blood Group": ["EDTA"],
  "ESR": ["EDTA"],
  "FBS": ["Fluoride"],
  "PP": ["Fluoride"],
  "RBS": ["Fluoride"],
  "Fasting Insuline": ["Fluoride"],
  "HbA1C": ["EDTA"],
  "LFT": ["Plain"],
  "Bilirubin-Total": ["Plain"],
  "Bilirubin-Direct": ["Plain"],
  "SGPT": ["Plain"],
  "SGOT": ["Plain"],
  "GGT": ["Fluoride"],
  "RFT": ["Plain"],
  "Creatinine": ["Plain"],
  "Urea": ["Plain"],
  "BUN": ["Plain"],
  "Uric Acid": ["Plain"],
  "Calcium": ["Plain"],
  "Lipid Profile": ["Plain"],
  "Total Cholestrol": ["Plain"],
  "HDL": ["Plain"],
  "LDL": ["Plain"],
  "LDH": ["Plain"],
  "Electrolytes": ["Plain"],
  "Sodium": ["Plain"],
  "Chlorides": ["Plain"],
  "Phosphorous": ["Plain"],
  "Potassium": ["Plain"],
  "Iron Study": ["Plain"],
  "Vit D3": ["Plain"],
  "Vit B12": ["Plain"],
  "T3, T4, TSH": ["Plain"],
  "TSH": ["Plain"],
  "FT3, FT4, TSH": ["Plain"],
  "CRP": ["Plain"],
  "HSCRP": ["Plain"],
  "CPK-MB": ["Plain"],
  "CPK-Total": ["Plain"],
  "Trop-I": ["Plain"],
  "D-Dimer": ["Citrate"],
  "PT INR": ["Citrate"],
  "ApTT": ["Citrate"],
  "HIV": ["Plain"],
  "HCV": ["Plain"],
  "HBsAg": ["Plain"],
  "VDRL": ["Plain"],
  "Triple H Package": ["Plain"],
  "Urine Culture": ["Urine"],
  "Urine Routine": ["Urine"],
  "RA Factor": ["Plain"],
  "MP": ["EDTA"],
  "Widal": ["Plain"],
  "Dengue NSI": ["Plain"],
  "Dengue IGG": ["Plain"],
  "Dengue IGM": ["Plain"],
  "MP-Antigen": ["EDTA"],
  "Beta HCG": ["Plain"],
  "Homocysten": ["EDTA"],
  "CA125 (Female)": ["Serum"],
  "PSA (Male)": ["Serum"],
  "IGE": ["Serum"],
  "Trop-T": ["Plain"],
  "Anti CCP": ["Plain"],
  "ANA": ["Plain"],
  "Total Protien": ["Plain"],
  "Covid Antibody": ["Plain"],
  "PP Insuline": ["Fluoride"],
  "CEA": ["Plain"],
  "AFPL": ["Serum"],
  "Hb Electrophoresis": ["EDTA"],
  "FT3": ["Plain"],
  "FT4": ["Plain"],
  "Urine Protein Creatinine Ratio": ["Urine"],
  "Protein with A/G Ratio": ["Plain"],
  "Lypase": ["Plain"],
  "PUS Culture (Aerobic)": ["Pus"],
  "FT3, FT4": ["Plain"],
  "Fecal Calprotectin": ["Stool"],
  "Blood Culture 1 SE": ["Blood Culture Bottle"],
  "Anti Pro MBP": ["EDTA"],
  "Total TFT": ["Plain"],
  "HBS Antigen": ["Plain"],
  "Reticulate Count": ["EDTA"],
  "Direct Coombs Test": ["EDTA"],
  "Microalbuminuria": ["Urine"],
  "Total Testosteron": ["Plain"],
  "Free Testosteron": ["Plain"],
  "Protein C": ["Plain"],
  "Protein S": ["Plain"],
  "Fibrinogen Level": ["Citrate"],
  "Folic Acid Level": ["Plain"],
  "Maleria Antigen": ["Plain"],
  "Urine Glucose (Fasting)": ["Urine"],
  "Factor V": ["EDTA"],
  "Ferritine": ["Plain"],
  "HAV": ["Plain"],
  "HEV": ["Plain"],
  "RA Test": ["Plain"],
  "Iron Profile with Ferritine": ["Plain"],
  "Allergy Drug Test": ["Plain"],
  "IGA TTG": ["Plain"],
  "PTT": ["Citrate"],
  "H. Pylori Stool": ["Stool"],
  "Chikungunya IgG": ["Plain"],
  "FBA": ["Plain"],
  "Protein Electrophoresis": ["Plain"],
  "Zinc Level": ["Plain"],
  "Magnesium": ["Plain"],
  "Estrogen": ["Plain"],
  "C-Peptide Random": ["Plain"],
  "B2 Glycoprotein 1 IgG": ["Plain"],
  "PSA Free & Total": ["Plain"],
  "LH": ["Plain"],
  "FSH": ["Plain"],
  "Semen Analysis": ["Semen Sample"]
};


/* ========================= Test Data per Lab ========================= */
const TESTS_DATA = {
lab1: [{ name: "CBC", mrp: 300, b2b: 80 },
{ name: "Blood Group", mrp: 180, b2b: 70 },
{ name: "ESR", mrp: 150, b2b: 60 },
{ name: "FBS", mrp: 80, b2b: 30 },
{ name: "PP", mrp: 80, b2b: 30 },
{ name: "RBS", mrp: 80, b2b: 30 },
{ name: "Fasting Insuline", mrp: 800, b2b: 350 },
{ name: "HbA1C", mrp: 550, b2b: 130 },
{ name: "LFT", mrp: 900, b2b: 220 },
{ name: "Bilirubin-Total", mrp: 190, b2b: 96 },
{ name: "Bilirubin-Direct", mrp: 190, b2b: 96 },
{ name: "SGPT", mrp: 190, b2b: 40 },
{ name: "SGOT", mrp: 190, b2b: 40 },
{ name: "GGT", mrp: 280, b2b: 182 },
{ name: "RFT", mrp: 1000, b2b: 570 },
{ name: "Creatinine", mrp: 190, b2b: 50 },
{ name: "Urea", mrp: 190, b2b: 108 },
{ name: "BUN", mrp: 190, b2b: 108 },
{ name: "Uric Acid", mrp: 190, b2b: 50 },
{ name: "Calcium", mrp: 190, b2b: 114 },
{ name: "Lipid Profile", mrp: 600, b2b: 185 },
{ name: "Total Cholestrol", mrp: 190, b2b: 108 },
{ name: "HDL", mrp: 220, b2b: 132 },
{ name: "LDL", mrp: 400, b2b: 240 },
{ name: "LDH", mrp: 500, b2b: 150 },
{ name: "Electrolytes", mrp: 180, b2b: 130 },
{ name: "Sodium", mrp: 180, b2b: 108 },
{ name: "Chlorides", mrp: 150, b2b: 90 },
{ name: "Phosphorous", mrp: 190, b2b: 114 },
{ name: "Potassium", mrp: 180, b2b: 108 },
{ name: "Iron Study", mrp: 800, b2b: 300 },
{ name: "Vit D3", mrp: 1300, b2b: 250 },
{ name: "Vit B12", mrp: 850, b2b: 250 },
{ name: "Total TFT", mrp: 550, b2b: 110 },
{ name: "TSH", mrp: 370, b2b: 50 },
{ name: "Free TFT", mrp: 650, b2b: 200 },
{ name: "CRP", mrp: 450, b2b: 150 },
{ name: "HSCRP", mrp: 850, b2b: 350 },
{ name: "CPK-MB", mrp: 850, b2b: 350 },
{ name: "CPK-Total", mrp: 550, b2b: 300 },
{ name: "Trop-I", mrp: 1200, b2b: 750 },
{ name: "D-Dimer", mrp: 1200, b2b: 500 },
{ name: "PT INR", mrp: 330, b2b: 120 },
{ name: "ApTT", mrp: 600, b2b: 330 },
{ name: "HIV", mrp: 600, b2b: 350 },
{ name: "HCV", mrp: 900, b2b: 525 },
{ name: "HBsAg", mrp: 550, b2b: 440 },
{ name: "VDRL", mrp: 370, b2b: 180 },
{ name: "Triple H", mrp: 1500, b2b: 650 },
{ name: "Urine Culture", mrp: 950, b2b: 400 },
{ name: "Urine Routine", mrp: 160, b2b: 60 },
{ name: "RA Factor", mrp: 500, b2b: 270 },
{ name: "MP", mrp: 120, b2b: 72 },
{ name: "Widal", mrp: 250, b2b: 150 },
{ name: "Dengue NSI", mrp: 800, b2b: 300 },
{ name: "Dengue IGG", mrp: 800, b2b: 300 },
{ name: "Dengue IGM", mrp: 800, b2b: 350 },
{ name: "MP-Antigen", mrp: 450, b2b: 315 },
{ name: "Beta HCG", mrp: 850, b2b: 200 },
{ name: "Homocysten", mrp: 1450, b2b: 500 },
{ name: "CA125 (Female)", mrp: 1200, b2b: 500 },
{ name: "PSA (Male)", mrp: 900, b2b: 350 },
{ name: "IGE", mrp: 950, b2b: 400 },
{ name: "Trop-T", mrp: 1500, b2b: 1050 },
{ name: "Anti CCP", mrp: 1550, b2b: 650 },
{ name: "ANA", mrp: 950, b2b: 500 },
{ name: "Total Protien", mrp: 250, b2b: 80 },
{ name: "Covid Antibody", mrp: 1000, b2b: 500 },
{ name: "FNAC", mrp: 1500, b2b: 1050 },
{ name: "PP Insuline", mrp: 850, b2b: 560 },
{ name: "CEA", mrp: 800, b2b: 400 },
{ name: "AFPL", mrp: 900, b2b: 450 },
{ name: "Hb Electrophoresis", mrp: 950, b2b: 450 },
{ name: "FT3", mrp: 280, b2b: 80 },
{ name: "FT4", mrp: 280, b2b: 80 },
{ name: "Urine Protein Creatinine Ratio", mrp: 420, b2b: 240 },
{ name: "Protein with A/G Ratio", mrp: 250, b2b: 80 },
{ name: "Lipase", mrp: 750, b2b: 300 },
{ name: "Estradiol", mrp: 780, b2b: 300 },
{ name: "PUS Culture (Aerobic)", mrp: 950, b2b: 400 },
{ name: "FT3  FT4", mrp: 560, b2b: 160 },
{ name: "Fecal Calprotectin", mrp: 2800, b2b: 2240 },
{ name: "Blood Culture 1 SE", mrp: 1500, b2b: 800 },
{ name: "NT-Pro BNP", mrp: 2500, b2b: 1100 },
{ name: "HBS Antigen", mrp: 550, b2b: 350 },
{ name: "Mantoux Test", mrp: 150, b2b: 135 },
{ name: "Reticulate Count", mrp: 400, b2b: 210 },
{ name: "Direct Coombs Test", mrp: 550, b2b: 150 },
{ name: "Microalbuminuria", mrp: 620, b2b: 250 },
{ name: "Total Testosteron", mrp: 780, b2b: 350 },
{ name: "Free Testosteron", mrp: 1550, b2b: 750 },
{ name: "Protein C", mrp: 4500, b2b: 4050 },
{ name: "Protein S", mrp: 4500, b2b: 4050 },
{ name: "Lupus Anticoagulant", mrp: 1800, b2b: 800 },
{ name: "Fibrinogen Level", mrp: 850, b2b: 400 },
{ name: "Anti dsDNA NCX", mrp: 1750, b2b: 1000 },
{ name: "Apolipoprotein A-1 & B", mrp: 1100, b2b: 770 },
{ name: "Folic Acid Level", mrp: 1100, b2b: 500 },
{ name: "Allergy Comprehensive", mrp: 5500, b2b: 3850 },
{ name: "Maleria Antigen", mrp: 450, b2b: 315 },
{ name: "Urine Glucose (Fasting)", mrp: 50, b2b: 30 },
{ name: "Factor V", mrp: 5500, b2b: 4400 },
{ name: "Ferritine", mrp: 950, b2b: 400 },
{ name: "HAV", mrp: 1200, b2b: 550 },
{ name: "HEV", mrp: 1500, b2b: 600 },
{ name: "RA Test", mrp: 500, b2b: 270 },
{ name: "Iron Profile with Ferritine", mrp: null, b2b: null },
{ name: "Allergy Drug Test", mrp: 7500, b2b: 5250 },
{ name: "IGA TTG", mrp: 800, b2b: 500 },
{ name: "Peripheral Smear", mrp: 150, b2b: 60 },
{ name: "PTT", mrp: 600, b2b: 330 },
{ name: "Cortisol 8 AM", mrp: 850, b2b: 350 },
{ name: "H. Pylori Stool", mrp: 1250, b2b: 960 },
{ name: "Chikungunya IgG", mrp: 900, b2b: 810 },
{ name: "FBA", mrp: null, b2b: null },
{ name: "Protein Electrophoresis", mrp: 1200, b2b: 500 },
{ name: "Sputum TB Culture & ABS", mrp: 150, b2b: 90 },
{ name: "Complement C3 & C4", mrp: null, b2b: null },
{ name: "DHEAS", mrp: 1150, b2b: 600 },
{ name: "DHEA", mrp: 3000, b2b: 2100 },
{ name: "Torch Complex", mrp: 2800, b2b: 1200 },
{ name: "Zinc Level", mrp: 2200, b2b: 1980 },
{ name: "Magnesium", mrp: 400, b2b: 280 },
{ name: "Estrogen", mrp: null, b2b: null },
{ name: "C-Peptide Random", mrp: 1150, b2b: 550 },
{ name: "B2 Glycoprotein 1 IgG", mrp: 1200, b2b: 500 },
{ name: "Karyotyping - Husband", mrp: 4000, b2b: 2800 },
{ name: "Karyotyping - Wife", mrp: 4000, b2b: 2800 },
{ name: "Influenza Screening for ABF", mrp: null, b2b: null },
{ name: "PSA Free & Total", mrp: 850, b2b: 350 },
{ name: "LH", mrp: 550, b2b: 180 },
{ name: "FSH", mrp: 550, b2b: 180 },
{ name: "Semen Analysis", mrp: 1100, b2b: 770 },
{ name: "Alkaline Phosphatase", mrp: null, b2b: null },
{ name: "Globulin", mrp: null, b2b: null },
{ name: "BUN / Creatinine Ratio", mrp: null, b2b: null },
{ name: "Urea/G Ratio", mrp: null, b2b: null },
{ name: "T3", mrp: 250, b2b: null },
{ name: "T4", mrp: 250, b2b: null },
{ name: "Stool  Routine", mrp: 170, b2b: 90 },
{ name: "Albumin", mrp: 400, b2b: 320 },
{ name: "Billirubin Indirect", mrp: null, b2b: null },
{ name: "Bicarbonate", mrp: null, b2b: null },
{ name: "Amylase", mrp: 700, b2b: 275 },
{ name: "ACTH", mrp: 1800, b2b: null },
{ name: "Throat Swab C/S", mrp: 950, b2b: 400 },
{ name: "ASO Titer", mrp: 650, b2b: 390 },
{ name: "AMH", mrp: 2000, b2b: 1000 },
{ name: "PTH ", mrp: 1600, b2b: 1120 },
{ name: "Apo B: Apo A1 ratio", mrp: null, b2b: null }],

lab2: [{ name: "CBC", mrp: 280, b2b: 168 },
{ name: "Blood Group", mrp: 150, b2b: 90 },
{ name: "ESR", mrp: 90, b2b: 54 },
{ name: "FBS", mrp: 70, b2b: 46 },
{ name: "PP", mrp: 70, b2b: 46 },
{ name: "RBS", mrp: 70, b2b: 46 },
{ name: "Fasting Insuline", mrp: 715, b2b: 501 },
{ name: "HbA1C", mrp: 520, b2b: 338 },
{ name: "LFT", mrp: 900, b2b: 585 },
{ name: "Bilirubin-Total", mrp: 200, b2b: 120 },
{ name: "Bilirubin-Direct", mrp: 200, b2b: 120 },
{ name: "SGPT", mrp: 180, b2b: 108 },
{ name: "SGOT", mrp: 180, b2b: 108 },
{ name: "GGT", mrp: 200, b2b: 126 },
{ name: "RFT", mrp: 1350, b2b: 878 },
{ name: "Creatinine", mrp: 180, b2b: 108 },
{ name: "Urea", mrp: 180, b2b: 108 },
{ name: "BUN", mrp: null, b2b: null },
{ name: "Uric Acid", mrp: 180, b2b: 108 },
{ name: "Calcium", mrp: 275, b2b: 176 },
{ name: "Lipid Profile", mrp: 550, b2b: 352 },
{ name: "Total Cholestrol", mrp: 180, b2b: 108 },
{ name: "HDL", mrp: 180, b2b: 106 },
{ name: "LDL", mrp: 320, b2b: 224 },
{ name: "LDH", mrp: 350, b2b: 263 },
{ name: "Electrolytes", mrp: 400, b2b: 240 },
{ name: "Sodium", mrp: null, b2b: null },
{ name: "Chlorides", mrp: null, b2b: null },
{ name: "Phosphorous", mrp: null, b2b: null },
{ name: "Potassium", mrp: null, b2b: null },
{ name: "Iron Study", mrp: 520, b2b: 333 },
{ name: "Vit D3", mrp: 1500, b2b: 450 },
{ name: "Vit B12", mrp: 950, b2b: 285 },
{ name: "Total TFT", mrp: 580, b2b: 232 },
{ name: "TSH", mrp: 320, b2b: 128 },
{ name: "Free TFT", mrp: 680, b2b: 272 },
{ name: "CRP", mrp: 500, b2b: 225 },
{ name: "HSCRP", mrp: 700, b2b: 420 },
{ name: "CPK-MB", mrp: 850, b2b: 536 },
{ name: "CPK-Total", mrp: 380, b2b: 236 },
{ name: "Trop-I", mrp: 770, b2b: 539 },
{ name: "D-Dimer", mrp: 1150, b2b: 736 },
{ name: "PT INR", mrp: 300, b2b: 195 },
{ name: "ApTT", mrp: 400, b2b: 240 },
{ name: "HIV", mrp: 400, b2b: 280 },
{ name: "HCV", mrp: 750, b2b: 600 },
{ name: "HBsAg", mrp: null, b2b: null },
{ name: "VDRL", mrp: 165, b2b: 106 },
{ name: "Triple H", mrp: null, b2b: null },
{ name: "Urine Culture", mrp: 800, b2b: 560 },
{ name: "Urine Routine", mrp: 110, b2b: 70 },
{ name: "RA Factor", mrp: 275, b2b: 176 },
{ name: "MP", mrp: 180, b2b: 106 },
{ name: "Widal", mrp: 165, b2b: 106 },
{ name: "Dengue NSI", mrp: 880, b2b: 563 },
{ name: "Dengue IGG", mrp: 880, b2b: 563 },
{ name: "Dengue IGM", mrp: 880, b2b: 563 },
{ name: "MP-Antigen", mrp: 500, b2b: 315 },
{ name: "Beta HCG", mrp: 500, b2b: 355 },
{ name: "Homocysten", mrp: 1200, b2b: 744 },
{ name: "CA125 (Female)", mrp: 1050, b2b: 683 },
{ name: "PSA (Male)", mrp: 750, b2b: 497 },
{ name: "IGE", mrp: 770, b2b: 539 },
{ name: "Trop-T", mrp: 770, b2b: 539 },
{ name: "Anti CCP", mrp: 1250, b2b: 813 },
{ name: "ANA", mrp: 950, b2b: 599 },
{ name: "Total Protien", mrp: 200, b2b: 120 },
{ name: "Covid Antibody", mrp: 500, b2b: 350 },
{ name: "FNAC", mrp: 800, b2b: 560 },
{ name: "PP Insuline", mrp: 715, b2b: 501 },
{ name: "CEA", mrp: 850, b2b: 578 },
{ name: "AFPL", mrp: 700, b2b: 462 },
{ name: "Hb Electrophoresis", mrp: null, b2b: null },
{ name: "FT3", mrp: 240, b2b: 120 },
{ name: "FT4", mrp: 240, b2b: 120 },
{ name: "Urine Protein Creatinine Ratio", mrp: null, b2b: null },
{ name: "Protein with A/G Ratio", mrp: null, b2b: null },
{ name: "Lipase", mrp: 700, b2b: 490 },
{ name: "Estradiol", mrp: 600, b2b: 414 },
{ name: "PUS Culture (Aerobic)", mrp: 800, b2b: 560 },
{ name: "FT3  FT4", mrp: 480, b2b: 240 },
{ name: "Fecal Calprotectin", mrp: 3000, b2b: 1920 },
{ name: "Blood Culture 1 SE", mrp: 1050, b2b: 735 },
{ name: "NT-Pro BNP", mrp: 2035, b2b: 1302 },
{ name: "HBS Antigen", mrp: null, b2b: null },
{ name: "Mantoux Test", mrp: 120, b2b: 71 },
{ name: "Reticulate Count", mrp: 180, b2b: 108 },
{ name: "Direct Coombs Test", mrp: 300, b2b: 177 },
{ name: "Microalbuminuria", mrp: 550, b2b: 352 },
{ name: "Total Testosteron", mrp: 600, b2b: 426 },
{ name: "Free Testosteron", mrp: 1600, b2b: 1440 },
{ name: "Protein C", mrp: 3300, b2b: 2640 },
{ name: "Protein S", mrp: 3300, b2b: 2640 },
{ name: "Lupus Anticoagulant", mrp: null, b2b: null },
{ name: "Fibrinogen Level", mrp: 700, b2b: 420 },
{ name: "Anti dsDNA NCX", mrp: 935, b2b: 598 },
{ name: "Apolipoprotein A-1 & B", mrp: 700, b2b: 385 },
{ name: "Folic Acid Level", mrp: 900, b2b: 612 },
{ name: "Allergy Comprehensive", mrp: null, b2b: null },
{ name: "Maleria Antigen", mrp: 500, b2b: 315 },
{ name: "Urine Glucose (Fasting)", mrp: null, b2b: null },
{ name: "Factor V", mrp: null, b2b: null },
{ name: "Ferritine", mrp: 750, b2b: 525 },
{ name: "HAV", mrp: 950, b2b: 665 },
{ name: "HEV", mrp: 1050, b2b: 693 },
{ name: "RA Test", mrp: 275, b2b: 176 },
{ name: "Iron Profile with Ferritine", mrp: null, b2b: null },
{ name: "Allergy Drug Test", mrp: null, b2b: null },
{ name: "IGA TTG", mrp: 1430, b2b: 1001 },
{ name: "Peripheral Smear", mrp: null, b2b: null },
{ name: "PTT", mrp: 300, b2b: 195 },
{ name: "Cortisol 8 AM", mrp: 600, b2b: 434 },
{ name: "H. Pylori Stool", mrp: 750, b2b: 458 },
{ name: "Chikungunya IgG", mrp: null, b2b: null },
{ name: "FBA", mrp: null, b2b: null },
{ name: "Protein Electrophoresis", mrp: 950, b2b: 608 },
{ name: "Sputum TB Culture & ABS", mrp: 800, b2b: 560 },
{ name: "Complement C3 & C4", mrp: null, b2b: null },
{ name: "DHEAS", mrp: 850, b2b: 587 },
{ name: "DHEA", mrp: null, b2b: null },
{ name: "Torch Complex", mrp: null, b2b: null },
{ name: "Zinc Level", mrp: null, b2b: null },
{ name: "Magnesium", mrp: 450, b2b: 284 },
{ name: "Estrogen", mrp: null, b2b: null },
{ name: "C-Peptide Random", mrp: null, b2b: null },
{ name: "B2 Glycoprotein 1 IgG", mrp: null, b2b: null },
{ name: "Karyotyping - Husband", mrp: null, b2b: null },
{ name: "Karyotyping - Wife", mrp: null, b2b: null },
{ name: "Influenza Screening for ABF", mrp: 1650, b2b: 1056 },
{ name: "PSA Free & Total", mrp: 1450, b2b: 1001 },
{ name: "LH", mrp: 525, b2b: 263 },
{ name: "FSH", mrp: 525, b2b: 263 },
{ name: "Semen Analysis", mrp: 300, b2b: 300 },
{ name: "Alkaline Phosphatase", mrp: null, b2b: null },
{ name: "Globulin", mrp: null, b2b: null },
{ name: "BUN / Creatinine Ratio", mrp: null, b2b: null },
{ name: "Urea/G Ratio", mrp: null, b2b: null },
{ name: "T3", mrp: null, b2b: null },
{ name: "T4", mrp: null, b2b: null },
{ name: "Stool  Routine", mrp: 110, b2b: 70 },
{ name: "Albumin", mrp: null, b2b: null },
{ name: "Billirubin Indirect", mrp: null, b2b: null },
{ name: "Bicarbonate", mrp: null, b2b: null },
{ name: "Amylase", mrp: null, b2b: null },
{ name: "ACTH", mrp: null, b2b: null },
{ name: "Throat Swab C/S", mrp: null, b2b: null },
{ name: "ASO Titer", mrp: null, b2b: null },
{ name: "AMH", mrp: 2050, b2b: 1415 },
{ name: "PTH ", mrp: 1320, b2b: 924 },
{ name: "Apo B: Apo A1 ratio", mrp: null, b2b: null }],

lab3: [{ name: "CBC", mrp: 190, b2b: 60 },
{ name: "Blood Group", mrp: 220, b2b: 50 },
{ name: "ESR", mrp: 200, b2b: 50 },
{ name: "FBS", mrp: 70, b2b: 15 },
{ name: "PP", mrp: 70, b2b: 15 },
{ name: "RBS", mrp: 70, b2b: 15 },
{ name: "Fasting Insuline", mrp: 770, b2b: 150 },
{ name: "HbA1C", mrp: 495, b2b: 60 },
{ name: "LFT", mrp: 1045, b2b: 150 },
{ name: "Bilirubin-Total", mrp: 130, b2b: 22 },
{ name: "Bilirubin-Direct", mrp: 130, b2b: 24 },
{ name: "SGPT", mrp: 190, b2b: 24 },
{ name: "SGOT", mrp: 190, b2b: 22 },
{ name: "GGT", mrp: 242, b2b: 60 },
{ name: "RFT", mrp: 900, b2b: 210 },
{ name: "Creatinine", mrp: 180, b2b: 22 },
{ name: "Urea", mrp: 165, b2b: 25 },
{ name: "BUN", mrp: 220, b2b: 60 },
{ name: "Uric Acid", mrp: 220, b2b: 22 },
{ name: "Calcium", mrp: 176, b2b: 22 },
{ name: "Lipid Profile", mrp: 715, b2b: 100 },
{ name: "Total Cholestrol", mrp: 180, b2b: 10 },
{ name: "HDL", mrp: 180, b2b: 10 },
{ name: "LDL", mrp: 300, b2b: 50 },
{ name: "LDH", mrp: 363, b2b: 60 },
{ name: "Electrolytes", mrp: 520, b2b: 140 },
{ name: "Sodium", mrp: 275, b2b: 40 },
{ name: "Chlorides", mrp: 275, b2b: 40 },
{ name: "Phosphorous", mrp: 275, b2b: 40 },
{ name: "Potassium", mrp: 220, b2b: 40 },
{ name: "Iron Study", mrp: 660, b2b: 150 },
{ name: "Vit D3", mrp: 1280, b2b: 200 },
{ name: "Vit B12", mrp: 990, b2b: 160 },
{ name: "Total TFT", mrp: 495, b2b: 60 },
{ name: "TSH", mrp: 275, b2b: 20 },
{ name: "Free TFT", mrp: 1045, b2b: 140 },
{ name: "CRP", mrp: 495, b2b: 150 },
{ name: "HSCRP", mrp: 750, b2b: 175 },
{ name: "CPK-MB", mrp: 715, b2b: 200 },
{ name: "CPK-Total", mrp: 385, b2b: 125 },
{ name: "Trop-I", mrp: 1200, b2b: 650 },
{ name: "D-Dimer", mrp: 1650, b2b: 375 },
{ name: "PT INR", mrp: 450, b2b: 105 },
{ name: "ApTT", mrp: 418, b2b: 200 },
{ name: "HIV", mrp: 475, b2b: 120 },
{ name: "HCV", mrp: 935, b2b: 99 },
{ name: "HBsAg", mrp: 450, b2b: 250 },
{ name: "VDRL", mrp: 220, b2b: 75 },
{ name: "Triple H", mrp: 1730, b2b: 350 },
{ name: "Urine Culture", mrp: 950, b2b: 120 },
{ name: "Urine Routine", mrp: 300, b2b: 100 },
{ name: "RA Factor", mrp: 495, b2b: 200 },
{ name: "MP", mrp: 275, b2b: 100 },
{ name: "Widal", mrp: 330, b2b: 60 },
{ name: "Dengue NSI", mrp: 660, b2b: 250 },
{ name: "Dengue IGG", mrp: 660, b2b: 275 },
{ name: "Dengue IGM", mrp: 660, b2b: 275 },
{ name: "MP-Antigen", mrp: 700, b2b: 100 },
{ name: "Beta HCG", mrp: 550, b2b: 160 },
{ name: "Homocysten", mrp: 1155, b2b: 400 },
{ name: "CA125 (Female)", mrp: 1155, b2b: 350 },
{ name: "PSA (Male)", mrp: 935, b2b: 300 },
{ name: "IGE", mrp: 825, b2b: 195 },
{ name: "Trop-T", mrp: 1800, b2b: 700 },
{ name: "Anti CCP", mrp: 1375, b2b: 385 },
{ name: "ANA", mrp: 750, b2b: 175 },
{ name: "Total Protien", mrp: 200, b2b: 22 },
{ name: "Covid Antibody", mrp: 700, b2b: 270 },
{ name: "FNAC", mrp: 1150, b2b: 330 },
{ name: "PP Insuline", mrp: 770, b2b: 150 },
{ name: "CEA", mrp: 715, b2b: 250 },
{ name: "AFPL", mrp: 750, b2b: 295 },
{ name: "Hb Electrophoresis", mrp: 600, b2b: 315 },
{ name: "FT3", mrp: 275, b2b: 60 },
{ name: "FT4", mrp: 300, b2b: 60 },
{ name: "Urine Protein Creatinine Ratio", mrp: 900, b2b: 150 },
{ name: "Protein with A/G Ratio", mrp: 400, b2b: 150 },
{ name: "Lipase", mrp: 620, b2b: 120 },
{ name: "Estradiol", mrp: 605, b2b: 165 },
{ name: "PUS Culture (Aerobic)", mrp: 1455, b2b: 945 },
{ name: "FT3  FT4", mrp: 575, b2b: 120 },
{ name: "Fecal Calprotectin", mrp: 3630, b2b: 2340 },
{ name: "Blood Culture 1 SE", mrp: 1045, b2b: 530 },
{ name: "NT-Pro BNP", mrp: 3450, b2b: 2500 },
{ name: "HBS Antigen", mrp: 450, b2b: 250 },
{ name: "Mantoux Test", mrp: null, b2b: null },
{ name: "Reticulate Count", mrp: 550, b2b: 20 },
{ name: "Direct Coombs Test", mrp: 825, b2b: 160 },
{ name: "Microalbuminuria", mrp: 800, b2b: 350 },
{ name: "Total Testosteron", mrp: 605, b2b: 100 },
{ name: "Free Testosteron", mrp: 1485, b2b: 340 },
{ name: "Protein C", mrp: 5350, b2b: 2600 },
{ name: "Protein S", mrp: 4950, b2b: 2600 },
{ name: "Lupus Anticoagulant", mrp: 2650, b2b: 600 },
{ name: "Fibrinogen Level", mrp: 1250, b2b: 900 },
{ name: "Anti dsDNA NCX", mrp: 1650, b2b: 200 },
{ name: "Apolipoprotein A-1 & B", mrp: null, b2b: null },
{ name: "Folic Acid Level", mrp: 1045, b2b: 160 },
{ name: "Allergy Comprehensive", mrp: null, b2b: null },
{ name: "Maleria Antigen", mrp: 700, b2b: 100 },
{ name: "Urine Glucose (Fasting)", mrp: 70, b2b: 25 },
{ name: "Factor V", mrp: 7086, b2b: 4200 },
{ name: "Ferritine", mrp: 800, b2b: 160 },
{ name: "HAV", mrp: 880, b2b: 275 },
{ name: "HEV", mrp: 1210, b2b: 375 },
{ name: "RA Test", mrp: 495, b2b: 200 },
{ name: "Iron Profile with Ferritine", mrp: null, b2b: null },
{ name: "Allergy Drug Test", mrp: 5900, b2b: 1700 },
{ name: "IGA TTG", mrp: 1210, b2b: 280 },
{ name: "Peripheral Smear", mrp: 300, b2b: 100 },
{ name: "PTT", mrp: 450, b2b: 105 },
{ name: "Cortisol 8 AM", mrp: 605, b2b: 295 },
{ name: "H. Pylori Stool", mrp: 1500, b2b: 1200 },
{ name: "Chikungunya IgG", mrp: 825, b2b: 500 },
{ name: "FBA", mrp: null, b2b: null },
{ name: "Protein Electrophoresis", mrp: 660, b2b: 350 },
{ name: "Sputum TB Culture & ABS", mrp: null, b2b: null },
{ name: "Complement C3 & C4", mrp: null, b2b: null },
{ name: "DHEAS", mrp: 1045, b2b: 275 },
{ name: "DHEA", mrp: 2965, b2b: 2150 },
{ name: "Torch Complex", mrp: 1430, b2b: 800 },
{ name: "Zinc Level", mrp: 880, b2b: 460 },
{ name: "Magnesium", mrp: 440, b2b: 50 },
{ name: "Estrogen", mrp: null, b2b: null },
{ name: "C-Peptide Random", mrp: null, b2b: null },
{ name: "B2 Glycoprotein 1 IgG", mrp: 1100, b2b: 660 },
{ name: "Karyotyping - Husband", mrp: 4400, b2b: 1500 },
{ name: "Karyotyping - Wife", mrp: 4400, b2b: 1500 },
{ name: "Influenza Screening for ABF", mrp: null, b2b: null },
{ name: "PSA Free & Total", mrp: 1760, b2b: 465 },
{ name: "LH", mrp: 495, b2b: 100 },
{ name: "FSH", mrp: 495, b2b: 100 },
{ name: "Semen Analysis", mrp: null, b2b: null },
{ name: "Alkaline Phosphatase", mrp: null, b2b: null },
{ name: "Globulin", mrp: null, b2b: null },
{ name: "BUN / Creatinine Ratio", mrp: null, b2b: null },
{ name: "Urea/G Ratio", mrp: null, b2b: null },
{ name: "T3", mrp: null, b2b: null },
{ name: "T4", mrp: null, b2b: null },
{ name: "Stool  Routine", mrp: 220, b2b: 60 },
{ name: "Albumin", mrp: null, b2b: null },
{ name: "Billirubin Indirect", mrp: null, b2b: null },
{ name: "Bicarbonate", mrp: null, b2b: null },
{ name: "Amylase", mrp: null, b2b: null },
{ name: "ACTH", mrp: null, b2b: null },
{ name: "Throat Swab C/S", mrp: null, b2b: null },
{ name: "ASO Titer", mrp: null, b2b: null },
{ name: "AMH", mrp: 2142, b2b: 600 },
{ name: "PTH ", mrp: 1450, b2b: null },
{ name: "Apo B: Apo A1 ratio", mrp: null, b2b: null }],

  lab4: [  ]
};

// For backward compatibility
const TESTS = TESTS_DATA.lab1.map(t => t.name);

/* ========================= Packages Data per Lab ========================= */
const PACKAGES = {
  lab1: [
    { name: "GOODNESS A1", tests: ["CBC", "FBS", "PP", "HbA1C", "Total TFT", "Iron Study", "Vit D3", "Vit B12", "Lipid Profile", "LFT", "RFT"], mrp: 2500, b2b: 1200 },
{ name: "GOODNESS E", tests: ["FBS", "PP", "HbA1C", "Lipid Profile", "Creatinine", "Uric Acid", "CBC"], mrp: 1000, b2b: 450 },
{ name: "GOODNESS G", tests: ["CBC", "FBS", "PP", "HbA1C", "Lipid Profile", "Creatinine", "Total TFT", "Uric Acid"], mrp: 1500, b2b: 550 },
{ name: "GOODNESS BB FEMALE", tests: ["CBC", "FBS", "HbA1C", "Lipid Profile", "HSCRP", "LFT", "RFT", "Fasting Insuline", "Vit B12", "Vit D3", "Total TFT", "Homocysten", "CA125 (Female)"], mrp: 3500, b2b: 1500 },
{ name: "GOODNESS BA MALE", tests: ["CBC", "FBS", "HbA1C", "Lipid Profile", "HSCRP", "LFT", "RFT", "Fasting Insuline", "Vit B12", "Vit D3", "Total TFT", "Homocysten", "PSA (Male)"], mrp: 3500, b2b: 1400 },
{ name: "GOODNESS C", tests: ["SGOT", "LDH", "CPK-MB", "Trop-I"], mrp: 2200, b2b: 1200 },
{ name: "GOODNESS F", tests: ["CBC", "HbA1C", "LFT", "Lipid Profile", "RFT"], mrp: 2000, b2b: 600 },
{ name: "GOODNESS 3H ", tests: ["HIV", "HCV", "HBsAg"], mrp: 1500, b2b: 650 },
{ name: "FEVER PROFILE", tests: ["CBC", "ESR", "SGPT", "SGOT", "CRP", "Dengue NSI", "Maleria Antigen", "Urine Routine", "Widal"], mrp: 3000, b2b: 950 }
],
  lab2: [
  ],
  lab3: [
    { name: "GD Life A1", tests: ["Iron Study", "RFT", "CBC", "LFT", "Lipid Profile", "Total TFT"], mrp: 1400, b2b: 295 },
{ name: "GD Life A3", tests: ["FBS", "LFT", "Lipid Profile", "TSH", "CBC", "RFT"], mrp: 1200, b2b: 230 },
{ name: "GD Wellness 1.3", tests: ["Total Testosteron", "Iron Study", "LFT", "Lipid Profile", "HbA1C", "Vit D3", "Vit B12", "Total TFT"], mrp: 1800, b2b: 600 },
{ name: "ALPHA WELLNESS 1.3", tests: ["Total Testosteron", "Iron Study", "LFT", "Lipid Profile", "HbA1C", "RFT", "Vit D3", "Vit B12", "CBC", "ESR", "CRP", "Total TFT"], mrp: 2150, b2b: 750 },
{ name: "COMPREHENSIVE FULL BODY CHECKUP", tests: ["CBC", "Vit B12", "Vit D3", "HBsAg", "Urine Routine", "Peripheral Smear", "ESR", "Electrolytes", "Iron Study", "LFT", "Lipid Profile", "CRP"], mrp: 2000, b2b: 1050 },
{ name: "GD WELLNESS 15.1", tests: ["Iron Study", "LFT", "Lipid Profile", "RFT", "Total TFT"], mrp: 1000, b2b: 550 },
{ name: "GD LIFE - A6", tests: ["Homocysten", "Iron Study", "LFT", "Lipid Profile", "Total TFT", "HbA1C", "RFT", "Vit B12", "Vit D3"], mrp: 1800, b2b: 750 },
{ name: "Summer Health Package", tests: ["Iron Study", "Total TFT", "LFT", "HbA1C", "RFT", "Vit D3", "Vit B12", "Lipid Profile", "Electrolytes", "CBC", "Urine Routine"], mrp: 2000, b2b: 700 },
{ name: "Tax Saver Health Package", tests: ["Vit D3", "Vit B12", "RA Factor", "ESR", "Electrolytes", "Iron Study", "LFT", "Lipid Profile", "Total TFT", "HbA1C", "RFT", "CBC", "HSCRP", "Apolipoprotein A-1 & B", "Apo B: Apo A1 ratio"], mrp: 2500, b2b: 950 }
],
  lab4: [
  ]
};

/* ========================= Helper Functions ========================= */
function getTubeTypesForTest(testName) {
  return TEST_TUBE_MAPPING[testName] || [];
}

function getTubeInfo(tubeType) {
  return TUBE_TYPES[tubeType] || { name: tubeType, displayName: tubeType, imageUrl: "https://via.placeholder.com/100x100/cccccc/ffffff?text=Unknown" };
}

function getSyringeInfo(syringeSize) {
  return SYRINGE_TYPES[syringeSize] || { name: syringeSize, displayName: syringeSize, imageUrl: "https://via.placeholder.com/100x100/cccccc/ffffff?text=Syringe" };
}

// Calculate unique tube counts per lab (each tube type counted once per lab)
// Then add +1 extra Fluoride tube if PP test exists in that lab
function calculateUniqueTubeCountsPerLab(tests) {
  const tubeSet = new Set();
  
  tests.forEach(test => {
    const tubeTypes = getTubeTypesForTest(test);
    tubeTypes.forEach(tubeType => tubeSet.add(tubeType));
  });
  
  const tubeCounts = {};
  tubeSet.forEach(tubeType => {
    tubeCounts[tubeType] = 1;
  });
  
  // Special handling for PP test: add exactly +1 additional Fluoride tube
  if (tests.includes("PP")) {
    if (tubeCounts["Fluoride"]) {
      tubeCounts["Fluoride"] += 1;
    } else {
      tubeCounts["Fluoride"] = 1;
    }
  }
  
  return tubeCounts;
}

// Calculate total tube counts across all labs (sum per lab)
function calculateTotalTubeCounts(labsData) {
  const totalCounts = {};
  
  labsData.forEach(lab => {
    const labCounts = calculateUniqueTubeCountsPerLab(lab.tests);
    for (const [tubeType, count] of Object.entries(labCounts)) {
      totalCounts[tubeType] = (totalCounts[tubeType] || 0) + count;
    }
  });
  
  return totalCounts;
}

// For backward compatibility
const TUBES = {};
Object.keys(TUBE_TYPES).forEach(key => {
  TUBES[TUBE_TYPES[key].name] = { name: TUBE_TYPES[key].name };
});

const TEST_TUBE_REQUIREMENTS = {};
Object.keys(TEST_TUBE_MAPPING).forEach(test => {
  TEST_TUBE_REQUIREMENTS[test] = {};
  TEST_TUBE_MAPPING[test].forEach(tubeType => {
    TEST_TUBE_REQUIREMENTS[test][tubeType] = true;
  });
});

const TUBE_IMAGES = {};
Object.keys(TUBE_TYPES).forEach(key => {
  TUBE_IMAGES[TUBE_TYPES[key].name] = TUBE_TYPES[key].imageUrl;
});

const SYRINGE_IMAGES = {};
Object.keys(SYRINGE_TYPES).forEach(key => {
  SYRINGE_IMAGES[key] = SYRINGE_TYPES[key].imageUrl;
});
